<?php
namespace ZinCelestial\Platform\Rewards;
use ZinCelestial\Platform\Core\Settings;
final class RewardsView{
 public static function balances($user_id){$items=array();if(!function_exists('mycred_get_types')||!function_exists('mycred_get_users_balance'))return $items;foreach((array)mycred_get_types() as $slug=>$label){$items[]=array('slug'=>sanitize_key($slug),'label'=>wp_strip_all_tags($label),'value'=>mycred_get_users_balance($user_id,$slug),'icon'=>'●');}return $items;}
 public static function badges($user_id){$items=array();if(!function_exists('gamipress_get_user_achievements'))return $items;$posts=(array)gamipress_get_user_achievements(array('user_id'=>$user_id,'limit'=>20));foreach($posts as $post){$id=is_object($post)&&isset($post->ID)?absint($post->ID):absint($post);if(!$id)continue;$items[]=array('id'=>$id,'label'=>get_the_title($id),'image'=>get_the_post_thumbnail($id,'thumbnail',array('loading'=>'lazy')));}return $items;}
 public static function limits($context){$map=array('activity'=>array('activity_balances','activity_badges'),'directory'=>array('directory_balances','directory_badges'),'profile'=>array('profile_balances','profile_badges'));return $map[$context]??$map['directory'];}
 public static function render($owner_type,$owner_id,$context='directory'){if(!Settings::get('rewards_enabled',1)||'user'!==$owner_type||!$owner_id)return;list($balance_key,$badge_key)=self::limits($context);$balances=array_slice(self::balances($owner_id),0,Settings::get($balance_key,3));$badges=array_slice(self::badges($owner_id),0,Settings::get($badge_key,3));if(!$balances&&!$badges)return;echo '<section class="zcp-rewards zcp-rewards--'.esc_attr(sanitize_html_class($context)).'" aria-label="'.esc_attr__('Rewards','zincelestial-platform').'">';if($balances){echo '<div class="zcp-rewards__balances">';foreach($balances as $item)echo '<span class="zcp-reward-balance"><strong>'.esc_html($item['value']).'</strong><span aria-hidden="true">'.esc_html($item['icon']).'</span><small>'.esc_html($item['label']).'</small></span>';echo '</div>';}if($badges){echo '<div class="zcp-rewards__badges">';foreach($badges as $item)echo '<span class="zcp-reward-badge" title="'.esc_attr($item['label']).'">'.($item['image']?wp_kses_post($item['image']):'<span aria-hidden="true">◆</span>').'<span class="screen-reader-text">'.esc_html($item['label']).'</span></span>';echo '</div>';}echo '</section>';}
}
