<?php
namespace ZinCelestial\Platform\Core;
use ZinCelestial\Platform\Admin\ControlCenter;use ZinCelestial\Platform\Compatibility\PluginRegistry;use ZinCelestial\Platform\Diagnostics\DiagnosticsService;use ZinCelestial\Platform\Diagnostics\NetworkDiagnostics;use ZinCelestial\Platform\Modules\ModuleRegistry;use ZinCelestial\Platform\Admin\FleetPage;use ZinCelestial\Platform\Network\PolicyController;use ZinCelestial\Platform\Fleet\FleetService;use ZinCelestial\Platform\Assets\OptimizationEngine;use ZinCelestial\Platform\Admin\AssetController;use ZinCelestial\Platform\Assets\Rules\RuleEngine;use ZinCelestial\Platform\Assets\AssetsManager;use ZinCelestial\Platform\Network\AggregationController;use ZinCelestial\Platform\Performance\PerformanceService;use ZinCelestial\Platform\Network\SettingsManager;
defined('ABSPATH')||exit;
final class Plugin {
 private static ?self $instance=null;private Container $container;private bool $booted=false;
 public static function instance():self{return self::$instance??=new self();}
 private function __construct(){$this->container=new Container();$this->container->set('compatibility',fn()=>PluginRegistry::instance());$this->container->set('fleet',fn()=>new FleetService());$this->container->set('optimization',fn()=>new OptimizationEngine());$this->container->set('assets',fn()=>new AssetsManager());$this->container->set('diagnostics',fn()=>new DiagnosticsService());$this->container->set('performance',fn()=>new PerformanceService());$this->container->set('network.diagnostics',fn()=>new NetworkDiagnostics());$this->container->set('network.settings',fn()=>new SettingsManager());$this->container->set('modules',function(){ $r=new ModuleRegistry();$r->seed();return $r;});}
 public function boot():void{if($this->booted)return;$this->booted=true;load_plugin_textdomain('zincelestial-platform',false,dirname(plugin_basename(ZCP_FILE)).'/languages');if(is_admin()){ControlCenter::instance()->register();(new AggregationController())->register();(new AssetController())->register();(new FleetPage())->register();(new PolicyController())->register();}(new RuleEngine())->register();do_action('zca_platform_ready',$this);}
 public function container():Container{return $this->container;}public function diagnostics():DiagnosticsService{return $this->container->get('diagnostics');}public function fleet():FleetService{return $this->container->get('fleet');}public function optimization():OptimizationEngine{return $this->container->get('optimization');}public function assets():AssetsManager{return $this->container->get('assets');}public function performance():PerformanceService{return $this->container->get('performance');}public function modules():ModuleRegistry{return $this->container->get('modules');}public function compatibility():PluginRegistry{return $this->container->get('compatibility');}
}
