<?php
namespace ZinCelestial\Platform\Admin;
use ZinCelestial\Platform\Core\Plugin;use ZinCelestial\Platform\Diagnostics\HealthRegistry;
defined('ABSPATH')||exit;
final class ControlCenter{
 private static ?self $instance=null;public static function instance():self{return self::$instance??=new self();}
 public function register():void{add_action('admin_menu',array($this,'menu'));add_action('admin_menu',array($this,'performance_menu'));add_action('admin_menu',array($this,'assets_menu'));add_action('network_admin_menu',array($this,'network_menu'));add_action('admin_enqueue_scripts',array($this,'assets'));}
 public function menu():void{add_menu_page(__('ZinCelestial Platform','zincelestial-platform'),__('ZinCelestial','zincelestial-platform'),'manage_options','zcp-control-center',array($this,'render'),'dashicons-shield-alt',58);}
 public function assets_menu():void{add_submenu_page('zcp-control-center',__('Assets Manager','zincelestial-platform'),__('Assets','zincelestial-platform'),'manage_options','zcp-assets',array($this,'render_assets'));}
 public function render_assets():void{if(!current_user_can('manage_options'))return;$r=Plugin::instance()->optimization()->inspect();echo '<div class="wrap zcp-admin"><header class="zcp-hero"><div><h1>'.esc_html__('Assets Manager','zincelestial-platform').'</h1><p>'.esc_html__('Simulation mode — no changes are applied from this screen.','zincelestial-platform').'</p></div></header><div class="zcp-summary"><article><strong>'.esc_html((string)count($r['graph']['nodes'])).'</strong><span>'.esc_html__('Assets','zincelestial-platform').'</span></article><article><strong>'.esc_html((string)count($r['graph']['edges'])).'</strong><span>'.esc_html__('Dependencies','zincelestial-platform').'</span></article><article><strong>'.esc_html((string)count($r['simulation']['results'])).'</strong><span>'.esc_html__('Simulated rules','zincelestial-platform').'</span></article></div><h2>'.esc_html__('Dependency Graph','zincelestial-platform').'</h2><div class="zcp-grid">';foreach($r['graph']['nodes'] as $n){echo '<article class="zcp-card"><h2>'.esc_html($n['handle']).'</h2><p>'.esc_html($n['type']).'</p><small>'.esc_html($n['src']).'</small></article>';}echo '</div><h2>'.esc_html__('Simulation Results','zincelestial-platform').'</h2><div class="zcp-grid">';foreach($r['simulation']['results'] as $x){echo '<article class="zcp-card"><h2>'.esc_html($x['handle']).'</h2><p>'.esc_html($x['would_apply']?__('Would apply','zincelestial-platform'):__('Blocked','zincelestial-platform')).'</p><small>'.esc_html($x['blocked_reason']).'</small></article>';}echo '</div></div>';}
 public function performance_menu():void{add_submenu_page('zcp-control-center',__('Performance Center','zincelestial-platform'),__('Performance','zincelestial-platform'),'manage_options','zcp-performance',array($this,'render_performance'));}
 public function render_performance():void{if(!current_user_can('manage_options'))wp_die(esc_html__('You do not have permission to access this page.','zincelestial-platform'));$r=Plugin::instance()->performance()->report();$score=Plugin::instance()->performance()->score($r);echo '<div class="wrap zcp-admin"><header class="zcp-hero"><div><h1>'.esc_html__('Performance Center','zincelestial-platform').'</h1><p>'.esc_html__('Read-only current-site performance observations','zincelestial-platform').'</p></div></header><div class="zcp-grid"><article class="zcp-card"><h2>'.esc_html__('Performance Score','zincelestial-platform').'</h2><p><strong>'.esc_html((string)$score).'/100</strong></p></article>';foreach($r as $group=>$values){if(!is_array($values))continue;echo '<article class="zcp-card"><h2>'.esc_html(ucfirst($group)).'</h2><ul>';foreach($values as $key=>$value){if(is_array($value))$value=count($value);echo '<li><strong>'.esc_html(ucwords(str_replace('_',' ',$key))).':</strong> '.esc_html(is_bool($value)?($value?'Yes':'No'):(string)$value).'</li>';}echo '</ul></article>';}echo '</div></div>';}
 public function network_menu():void{if(is_multisite())add_menu_page(__('ZinCelestial Network','zincelestial-platform'),__('ZinCelestial','zincelestial-platform'),'manage_network_options','zcp-network',array($this,'render_network'),'dashicons-networking',58);}
 public function assets(string $hook):void{if(false===strpos($hook,'zcp-'))return;wp_enqueue_style('zcp-control-center',ZCP_URL.'assets/admin/control-center.css',array(),ZCP_VERSION);wp_enqueue_script('zcp-control-center',ZCP_URL.'assets/admin/control-center.js',array(),ZCP_VERSION,true);}
 private function badge(string $status):string{$map=array('ok'=>__('Healthy','zincelestial-platform'),'warning'=>__('Warning','zincelestial-platform'),'error'=>__('Error','zincelestial-platform'),'inactive'=>__('Inactive','zincelestial-platform'));return '<span class="zcp-badge zcp-badge--'.esc_attr($status).'">'.esc_html($map[$status]??ucfirst($status)).'</span>';}
 public function render():void{if(!current_user_can('manage_options'))wp_die(esc_html__('You do not have permission to access this page.','zincelestial-platform'));$report=Plugin::instance()->diagnostics()->report();$registry=new HealthRegistry();$cards=$registry->normalize($report);$counts=$registry->counts($cards);echo '<div class="wrap zcp-admin"><header class="zcp-hero"><div><h1>'.esc_html__('ZinCelestial Platform','zincelestial-platform').'</h1><p>'.esc_html(sprintf(__('Diagnostics Center · Core %s','zincelestial-platform'),ZCP_VERSION)).'</p></div><button class="button" type="button" data-zcp-copy>'.esc_html__('Copy report','zincelestial-platform').'</button></header><nav class="zcp-tabs"><button class="is-active" data-tab="overview">'.esc_html__('Overview','zincelestial-platform').'</button><button data-tab="integrations">'.esc_html__('Integrations','zincelestial-platform').'</button><button data-tab="environment">'.esc_html__('Environment','zincelestial-platform').'</button></nav><section data-panel="overview"><div class="zcp-summary">';foreach($counts as $key=>$value)echo '<article><strong>'.esc_html((string)$value).'</strong><span>'.esc_html(ucfirst($key)).'</span></article>';echo '</div></section><section data-panel="integrations" hidden><div class="zcp-grid">';foreach($cards as $card){$status=$card['active']?$card['status']:'inactive';echo '<article class="zcp-card"><div class="zcp-card__head"><h2>'.esc_html($card['label']).'</h2>'.$this->badge($status).'</div><ul>';foreach($card['capabilities'] as $cap)echo '<li>'.esc_html(ucwords(str_replace('-',' ',$cap))).'</li>';echo '</ul></article>';}echo '</div></section><section data-panel="environment" hidden><div class="zcp-grid">';foreach(array_merge($report['platform']??array(),$report['theme']??array(),$report['multisite']??array()) as $key=>$value){if(is_array($value))continue;echo '<article class="zcp-card"><h2>'.esc_html(ucwords(str_replace('_',' ',$key))).'</h2><p>'.esc_html(is_bool($value)?($value?'Yes':'No'):(string)$value).'</p></article>';}echo '</div><textarea class="zcp-report" readonly>'.esc_textarea(wp_json_encode($report,JSON_PRETTY_PRINT)).'</textarea></section></div>';}
 public function render_network():void{if(!current_user_can('manage_network_options'))wp_die(esc_html__('You do not have permission to access this page.','zincelestial-platform'));$service=Plugin::instance()->container()->get('network.diagnostics');$summary=$service->summary();echo '<div class="wrap zcp-admin"><header class="zcp-hero"><div><h1>'.esc_html__('ZinCelestial Network Diagnostics','zincelestial-platform').'</h1><p>'.esc_html__('Read-only network health summary','zincelestial-platform').'</p></div></header><div class="zcp-grid">';foreach($summary as $key=>$value)echo '<article class="zcp-card"><h2>'.esc_html(ucwords(str_replace('_',' ',$key))).'</h2><p>'.esc_html(is_bool($value)?($value?'Yes':'No'):(string)$value).'</p></article>';echo '</div></div>';}
}
